baseurl = "http://guizmo51.github.io/"
languageCode = "fr-fr"
title = "Simon Blum"
[[menu.main]]
url="/apropos"
name="Edito"
[[menu.main]]
url="/quisuisje"
name="Qui suis-je?"
[[menu.main]]
url="/retours-dexperiences"
name="Retours d'expériences"
title="Retours d'expériences"
[[menu.main]]
url="/hacks"
name="Hacks"
title="Hacks"
[[menu.main]]
url="/hors-sujet"
name="Hors-sujet"
title="Hors-sujet"
